### ISSUE TITLE
AARCH64 Question/issue

### ISSUE THREAD

**Issue by Craigy117** [spiritLHLS/proxylite-one-click-command-installation#3]
Hi, so I've tried to set this up on docker on an Orange Pi 3 LTS (AARCH64 (which I believe is just ARM64) and I get the following: 

exec /bin/sh: exec format error

Have you come across this before? I copied the setup instructions and pasted in my own ID etc

**Comment by spiritLHLS** [comment]
You need to have at least bash installed on your device first, or in the case of the apt manager, you need to ```apt install bash -y``` beforehand

**Comment by rcky844** [comment]
There is no aarch64 support for the docker image.
If you want to run it on a aarch64, you need `tonistiigi/binfmt`, note that performance will take a hit as it uses qemu to emulate for amd64.
On a Qualcomm MSM8916, it uses so much resources that it can kill my sshd sessions for RAM, as the devs used dotnet for development.
